language: node_js
node_js:
  - 8

cache:
  directories:
    - node_modules

env:
  # encrypted snyk token
  secure: oZ8fih46AQl5kY0Rxk/wmA3fBS2rZwyJmlBZQmOk39INWPE6LpgxtNumJnNC1txMXQC7qyZbLDamdxiPrqFh8/js0bIpI1ZolAVnZ2BSPKMtc9Vx9fyLGpHkZVT/Zp/C2e+ouXXrwI+lSwIAcevj9xCx2QnxPxCKFdSt6T6/sQmdZg5jcBrJGdL1j1tHtyLB6Ugk6lc3S7jVcvCVRazaMyeXnc2+FkxHbFMfdcfUU03aOoaeObKfhcqi7PfjEYkNMFgX097JdtA/pdiaAaiSMlI6rYDc5Oo1S82SK4a3FcJ3m3PoeRJslh/orN5QPFTHMu4NcOPTMWnXHcFzk9970ap04U6/EjdfzYH/57+HvuZpIHdKLuAKsT+teJIYCqZ7v0aY79wpDeJivZCCw9rQs0kAwgc8zx4xY7sWKq6Uw9rxKI6RG+Ut0JiU+a4XDLYYS51pBA07p/CEp+n80WvIbLhCBJpsNJeFe5a0I5C+J+yC2BhfVkG6e3Agn1PkrF43HVMbyvHOlXaaPQ7sbARMQApyi1xI5zJltC7fmdyAn/OgC6Ug80e5FvZ/wGeTCW+IK6cRvSsv3QhPnmMWHxMe3zzL8a8mp6QiVgQjr11/PYNhp2aQvigJzMPlDoOlI/6sv+KD4FQV0hbItaluXZtRLPRHdOvFWsK5TXFGcd28mtg=

install:
  - yarn add coveralls snyk

script:
  # send coverage to coveralls (http://coveralls.io/)
  - jest --coverage --coverageReporters=text-lcov --detectOpenHandles --forceExit | coveralls
  - yarn build

deploy:
  provider: heroku
  skip_cleanup: true
  app:
    master: graphql-songs-api-staging
    production: graphql-songs-api
  api_key:
    # encrypted heroku api key
    secure: ZlD+l/w8IPFL6bwShIgCpyWF1H/Ata10wX/3RCpo9dgQWONY1iwQkBZ8KvJ/VNb8QHOcxJgJvWlrtTlfM8d5qSp2ZjxVMphnakXdmTKKaGlNGs4usk52YdI3ROevKWtk8IDSu7UIRXLqtMJnSlhUcgjLheCq/6eKlYwZQdoHO3rzoz16uVwh/1jirf1jwhUXFRlGp8gXgm4LXNIE2eZdR8nqDUtJMkJ2ekAB25zOGY97ZSCj+3ti6O/kAsg2GRprohp7J0nQaAPqO/Blh+rgr3BG3r4fTjGEYTg8Pbo3JH7SDah+29+eW0o9icqHVDYBoQoon9uXougjlN9xHcwJtziUNPn4vJyDNoxVDivPCfhA/5E6jOJR+NCFXV23l0f0qlE5Txd44tMIL+D0OwRGw2aJvpeLG0acF/WNvrz3Htpn0D2WgXJAgXM12UEBCOG0DF3LT2rX2b3z43rfZfLW7dNGlFiZeMuQ4I8tJezt5t/nzBdqD6g1Emu3RPTxfEmbcCHObROZX0YC46qTp6jDP0fTQ+KFd8jnAJWt2VYa2+OF4cipxuD6tzrxFAlGgcZMQcl10WNsAm+TrRVlV/Nmm2QUjO2ZU+d3oq9lwbHmVtDoW11JUVQzyjSC0hEMyvpx0/a9D2uqvHzH3WJQaPpntAakykgfgeUaOgE0MB9U004=

after_deploy:
  - snyk monitor

notifications:
      email:
            recipients:
              - bstenm@hotmail.com
            on_success: change
            on_failure: change